# Generated by Django 3.1 on 2021-11-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_username'),
        ('accounts', '0005_auto_20211115_1742'),
    ]

    operations = [
    ]
